# Workflow to publish Godot HTML5 games to GitHub Pages
#
# This script assumes that the project itself is in a subdirectory "project". This
# folder structure frees up the root of the repository to be used for non-project
# files, such as the README, build folder, or raw assets folder.
#
# Make sure your project is configured for Web export
# to the path `build/web`.

name: 'Publish to GitHub Pages'

env:
  GODOT_VERSION: 4.1.1 # Remember to manually set image to this version below.

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  deploy-gh-page:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p ./web
          godot -v --export "HTML5" ./web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: ./web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./web # The folder the action should deploy.